# fly.toml app configuration file generated for rough-cloud-5890 on 2023-08-24T00:10:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-cloud-5890"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
