#! /usr/bin/env node

console.log(
  'This script populates some categories, brands and components to your database. Specified database as argument - e.g.: node populatedb "mongodb+srv://cooluser:coolpassword@cluster0.lz91hw2.mongodb.net/local_library?retryWrites=true&w=majority"'
);

// Get arguments passed on command line
const userArgs = process.argv.slice(2);

const Category = require("./models/category");
const Brand = require("./models/brand");
const Component = require("./models/component");

const categories = {};
const brands = {};
const components = {};

const mongoose = require("mongoose");
mongoose.set("strictQuery", false); // Prepare for Mongoose 7

const mongoDB = userArgs[0];

main().catch((err) => console.log(err));

async function main() {
  console.log("Debug: About to connect");
  await mongoose.connect(mongoDB);
  console.log("Debug: Should be connected?");
  await createCategories();
  await createBrands();
  await createComponents();
  console.log("Debug: Closing mongoose");
  mongoose.connection.close();
}

async function brandCreate(name, description) {
  const brand = new Brand({ name, description });
  await brand.save();
  brands[name] = brand;
  console.log(`Added brand: ${name}`);
}

async function categoryCreate(name, description) {
  const category = new Category({ name, description });
  await category.save();
  categories[name] = category;
  console.log(`Added category: ${name}`);
}

async function componentCreate(name, category, brand, description, price, imgUrl) {
  const component = new Component(name, category, brand, description, price, imgUrl);
  await component.save();
  components.push(component);
  console.log(`Added component: ${name}`);
}

async function createCategories() {
  console.log("Adding categories");
  await Promise.all([
    categoryCreate("CPU", "A central processing unit (CPU) is the most important processor in a given computer. Its electronic circuitry executes instructions of a computer program, such as arithmetic, logic, controlling, and input/output (I/O) operations."),
    categoryCreate("CPU Cooler", "CPU coolers are heat sinks which are specifically designed to remove waste heat generated by a central processing unit (CPU). They may include integral fans for active cooling and often fit standard CPU sockets."),
    categoryCreate("Motherboard", "A motherboard the main printed circuit board (PCB) in general-purpose computers and other expandable systems. It holds and allows communication between many of the crucial electronic components of a system, such as the central processing unit (CPU) and memory, and provides connectors for other peripherals."),
    categoryCreate("Memory", "Random-access memory (RAM) is a form of computer memory that can be read and changed in any order, typically used to store working data and machine code."),
    categoryCreate("Storage", "Computer data storage is a technology consisting of computer components and recording media that are used to retain digital data. It is a core function and fundamental component of computers."),
    categoryCreate("Video Card", "A graphics card (also called a video card, display card, graphics adapter, VGA card/VGA, video adapter, display adapter, or colloquially GPU) is a computer expansion card that generates a feed of graphics output to a display device such as a monitor."),
    categoryCreate("Case", "A computer case safeguards all of the important and expensive parts of a PC or other computing device."),
    categoryCreate("Power Supply", "A power supply unit (PSU) converts mains AC to low-voltage regulated DC power for the internal components of a computer. Modern personal computers universally use switched-mode power supplies."),
  ]);
}

async function createBrands() {
  console.log("Adding brands");
  await Promise.all([
    brandCreate("Asus", "ASUS is a top computer hardware and electronics company. It makes motherboards, graphics cards, components, peripherals, smartphones, tablets, laptops, headphones, routers, modems, and more. Asus is known for its high quality and robust products and has a very good reputation worldwide."),
    brandCreate("MSI", "MSI or Micro-Star International is a well-known computer hardware company that makes high-performance graphics cards. MSI makes both Nvidia and AMD graphics cards."),
    brandCreate("Gigabyte", "Gigabyte is a good brand that makes a variety of computer hardware products including motherboard, graphics cards, laptops, and other computer peripherals and components."),
    brandCreate("EVGA", "EVGA is an American Hardware manufacturer that makes Nvidia Graphics Cards, Power Supplies, and computer components and peripherals. EVGA makes high-quality Nvidia Graphics Cards but its availability is a bit of concern outside America."),
    brandCreate("Zotac", "Zotac is a company that is known for its cost-effective graphics cards and mini PCs. Zotac only makes Nvidia Graphics Cards and their graphics cards are affordable as compared to graphics cards from other big brands like Asus, MSI, Gigabyte, and EVGA."),
    brandCreate("Galax", "Galax (previous Galaxy) is a pretty decent company that makes affordable and reliable Nvidia graphics cards. Galax offers a complete range of graphics cards from Nvidia and they are a bit cheaper and more affordable than the more famous brands."),
    brandCreate("PNY", "PNY is an American company that makes graphics cards, flash memory cards, flash drives, chargers, adapters, and other accessories. PNY makes both gaming and workstation graphics cards for Nvidia."),
    brandCreate("Palit", "Palit is a graphics card manufacturer that mainly makes Nvidia Graphics Cards. It is a fairly popular brand and offers some cheap graphics cards."),
    brandCreate("PowerColor", "PowerColor is an AMD Radeon Graphics Cards manufacturer from Taiwan. It is a good brand and if you are looking for an AMD Graphics Card then PowerColor is one of the best."),
    brandCreate("Sapphire", "Sapphire also makes AMD Graphics Cards. It offers AMD Radeon graphics cards from all ranges including budget, mid-range, and high-end graphics cards. Sapphire is one of the most popular brands for AMD Radeon graphics cards."),
    brandCreate("Inno3D", "Inno3D is a Chinese manufacturer of Nvidia Graphics Cards. Their graphics cards offer good performance but they are a bit hard to find because of availability issues."),
    brandCreate("XFX", "XFX used to make Nvidia graphics cards previously but it is no longer an official Nvidia Partner and now it only makes AMD Graphics Cards. XFX Graphics Cards are pretty good and offer great performance and features."),
    brandCreate("HIS", "HIS is a graphics card manufacturer that makes AMD Radeon Graphics Cards."),
    brandCreate("VisionTek", "VisionTek is a manufacturer of AMD Radeon Graphics Cards. Their graphics cards are not very popular among gamers and also they are not readily available."),
    brandCreate("ASRock", "ASRock, which is known for its motherboards manufactures AMD Radeon Gaming Graphics Cards. Their graphics card series or range is known as Phantom Gaming."),
    brandCreate("AFOX", "AFOX is a Hong Kong-based company that manufactures both Nvidia and AMD graphics cards. It also manufactures Motherboards, Memory, SSD, CPU cooler, Power Supply, Mini-PC, Tablet PC, and Laptops."),
    brandCreate("Manli", "Manli Technology Group Ltd. is one of the major manufacturers and suppliers of Computer Graphics Cards, MiniPCs, 3D Printers, and other peripherals/components. It is a Hong Kong-based company and makes only Nvidia graphics cards."),
    brandCreate("AMD", "Advanced Micro Devices, Inc., commonly abbreviated as AMD, is an American multinational semiconductor company based in Santa Clara, California, that develops computer processors and related technologies for business and consumer markets."),
    brandCreate("Intel", "Intel Corporation (commonly known as Intel) is an American multinational corporation and technology company headquartered in Santa Clara, California. It is one of the world's largest semiconductor chip manufacturer by revenue, and is one of the developers of the x86 series of instruction sets found in most personal computers (PCs)."),
    brandCreate("Nvidia", "Nvidia Corporation is an American multinational technology company incorporated in Delaware and based in Santa Clara, California. It is a software and fabless company which designs graphics processing units (GPUs), application programming interface (APIs) as well as system on a chip units (SoCs)."),     
    brandCreate("Be Quiet!", "Be Quiet! is a computer hardware brand owned by the German company Listan GmbH, which manufactures power supply units, CPU coolers, computer cases and case fans. The main target groups for products in the be quiet! range are PC enthusiasts and gamers as well as smaller and larger PC integrators."),    
    brandCreate("Thermaltake", "Thermaltake Technology Co. Ltd is a Taiwanese manufacturer of PC case designs, power supplies, cooling devices and peripherals. Its main headquarters are located in Taipei, Taiwan. It has multiple manufacturing facilities in mainland China, including a major plant at Dongguan."),    
    brandCreate("Thermalright", "Thermalright Inc. is a Taiwan-based company headquartered in Taipei, and established in 2001. The company produces aftermarket heat sinks and other components for cooling desktop computers."),    
    brandCreate("Deepcool", "DeepCool is a computer hardware manufacturer headquartered in Beijing, China. Founded in 1996, the company produces a range of products including air and water CPU coolers, computer cases, power supplies, computer peripherals, and accessories."),    
    brandCreate("Noctua", "Noctua is an Austrian computer hardware manufacturer of CPU-coolers and computer fans which is primarily aimed at the enthusiast market. "),    
    brandCreate("Zalman", "Zalman Tech Co. (usually simplified as ZALMAN) is a South Korean company that develops and provides aftermarket desktop computer products with primary focus on cooling enhancement."),    
    brandCreate("Cooler Master", "Cooler Master Technology Inc. is a computer hardware manufacturer based in Taiwan. Founded in 1992, the company produces computer cases, power supplies, air and liquid CPU coolers, laptop cooling pads, and computer peripherals."),
    brandCreate("Corsair", "Corsair Gaming, Inc. is an American computer peripherals and hardware company based in Milpitas, California. It designs and sells high-speed DRAM modules, ATX power supplies (PSUs), USB flash drives (UFDs), CPU/GPU and case cooling and gaming peripherals."),
    brandCreate("NZXT", "NZXT is an American computer hardware manufacturer based in Los Angeles, California. The company manufactures computer cases, components, and accessories for the PC gaming market."),
    brandCreate("Kingston", "Kingston Technology Corporation is an American multinational computer technology corporation that develops, manufactures, sells and supports flash memory products, other computer-related memory products, as well as the HyperX gaming division (now owned by HP)."),
    brandCreate("GSkill", "G.SKILL International Enterprise is a Taiwanese computer hardware manufacturing company.[1] The company's target customers are overclocking computer users. It produces a variety of high-end PC products and is best known for its DRAM products."),
    brandCreate("Adata", "ADATA Technology Co. Ltd. is a Taiwanese fabless memory, storage and computer case manufacturer, founded in May 2001 by Simon Chen. Its main product line consists of DRAM modules, USB Flash drives, hard disk drives, solid state drives, memory cards and mobile accessories."),    
    brandCreate("Silicon Power", "Silicon Power Computer & Communications Incorporated, is an international brand and a Taiwan-based manufacturer of flash memory products, including flash memory cards, USB flash drives, portable hard drives, DRAM modules, card readers, solid state drives, USB adapters, and other industrial grade computer products."),
    brandCreate("Seagate", "Seagate Technology Holdings plc is an American data storage company. It was incorporated in 1978 as Shugart Technology and commenced business in 1979. Seagate developed the first 5.25-inch hard disk drive (HDD), the 5-megabyte ST-506, in 1980."),
    brandCreate("Western Digital", "Western Digital Corporation is an American computer drive manufacturer and data storage company, headquartered in San Jose, California. It designs, manufactures and sells data technology products, including data storage devices, data center systems and cloud storage services."),    
    brandCreate("Lian Li", "Lian Li Industrial Co., Ltd. is a Taiwanese computer case and accessories manufacturer. It is one of the largest manufacturers of aluminium computer cases in Taiwan and is also a major world competitor in the premium aftermarket computer case industry."),
    brandCreate("Fractal Design", "Fractal Design is a computer hardware manufacturer from Sweden. Founded in 2007, the company manufactures computer cases, water coolers, case fans, and power supplies. All products are designed and engineered in Sweden."),    
    brandCreate("Phanteks", "Phanteks is a Dutch company which mainly produces PC cases, fans and other case accessories. The company has a base in the United States."),    
  ]);
}

async function createComponents() {
  console.log("Adding Components");
  await Promise.all([
    componentCreate(
      "GeForce RTX™ 2070 GAMING OC 8G (rev. 1.0)",
      categories["Video Card"],
      brands["Gigabyte"],
      "Powered by GeForce RTX™ 2070, Integrated with 8GB GDDR6 256-bit memory interface WINDFORCE 3X Cooling System with alternate spinning fans RGB Fusion 2.0 Metal Back Plate",
      319.99,
      "/images/RTX2070Gigabyte.jpg"
    ),
  ]);
}
