#! /usr/bin/env node

console.log(
  'This script populates some categories, brands and components to your database. Specified database as argument - e.g.: node populatedb "mongodb+srv://cooluser:coolpassword@cluster0.lz91hw2.mongodb.net/local_library?retryWrites=true&w=majority"'
);

// Get arguments passed on command line
const userArgs = process.argv.slice(2);

const Category = require("./models/category");
const Brand = require("./models/brand");
const Component = require("./models/component");

const categories = {};
const brands = {};
const components = {};

const mongoose = require("mongoose");
mongoose.set("strictQuery", false); // Prepare for Mongoose 7

const mongoDB = userArgs[0];

main().catch((err) => console.log(err));

async function main() {
  console.log("Debug: About to connect");
  await mongoose.connect(mongoDB);
  console.log("Debug: Should be connected?");
  await createCategories();
  await createBrands();
  await createComponents();
  console.log("Debug: Closing mongoose");
  mongoose.connection.close();
}

async function brandCreate(name, description) {
  const brand = new Brand({ name, description });
  await brand.save();
  brands[name] = brand;
  console.log(`Added brand: ${name}`);
}

async function categoryCreate(name, description) {
  const category = new Category({ name, description });
  await category.save();
  categories[name] = category;
  console.log(`Added category: ${name}`);
}

async function componentCreate(name, category, brand, description, price, imgUrl) {
  const component = new Component( {name, category, brand, description, price, imgUrl} );
  await component.save();
  components[name] = component;
  console.log(`Added component: ${name}`);
}

async function createCategories() {
  console.log("Adding categories");
  await Promise.all([
    categoryCreate(
      "CPU", 
      "A central processing unit (CPU) is the most important processor in a given computer. Its electronic circuitry executes instructions of a computer program, such as arithmetic, logic, controlling, and input/output (I/O) operations."
    ),
    categoryCreate(
      "CPU Cooler", 
      "CPU coolers are heat sinks which are specifically designed to remove waste heat generated by a central processing unit (CPU). They may include integral fans for active cooling and often fit standard CPU sockets."
    ),
    categoryCreate(
      "Motherboard", 
      "A motherboard the main printed circuit board (PCB) in general-purpose computers and other expandable systems. It holds and allows communication between many of the crucial electronic components of a system, such as the central processing unit (CPU) and memory, and provides connectors for other peripherals."
    ),
    categoryCreate(
      "Memory", 
      "Random-access memory (RAM) is a form of computer memory that can be read and changed in any order, typically used to store working data and machine code."),
    categoryCreate(
      "Storage", 
      "Computer data storage is a technology consisting of computer components and recording media that are used to retain digital data. It is a core function and fundamental component of computers."
    ),
    categoryCreate(
      "Video Card", 
      "A graphics card (also called a video card, display card, graphics adapter, VGA card/VGA, video adapter, display adapter, or colloquially GPU) is a computer expansion card that generates a feed of graphics output to a display device such as a monitor."
    ),
    categoryCreate(
      "Case", 
      "A computer case safeguards all of the important and expensive parts of a PC or other computing device."
    ),
    categoryCreate(
      "Power Supply", 
      "A power supply unit (PSU) converts mains AC to low-voltage regulated DC power for the internal components of a computer. Modern personal computers universally use switched-mode power supplies."
    ),
  ]);
}

async function createBrands() {
  console.log("Adding brands");
  await Promise.all([
    brandCreate(
      "MSI", 
      "MSI or Micro-Star International is a well-known computer hardware company that makes high-performance graphics cards. MSI makes both Nvidia and AMD graphics cards."
    ),
    brandCreate(
      "Gigabyte", 
      "Gigabyte is a good brand that makes a variety of computer hardware products including motherboard, graphics cards, laptops, and other computer peripherals and components."
    ),
    brandCreate(
      "EVGA", 
      "EVGA is an American Hardware manufacturer that makes Nvidia Graphics Cards, Power Supplies, and computer components and peripherals. EVGA makes high-quality Nvidia Graphics Cards but its availability is a bit of concern outside America."
    ),
    brandCreate(
      "Zotac", 
      "Zotac is a company that is known for its cost-effective graphics cards and mini PCs. Zotac only makes Nvidia Graphics Cards and their graphics cards are affordable as compared to graphics cards from other big brands like Asus, MSI, Gigabyte, and EVGA."
    ),
    brandCreate(
      "Galax", 
      "Galax (previous Galaxy) is a pretty decent company that makes affordable and reliable Nvidia graphics cards. Galax offers a complete range of graphics cards from Nvidia and they are a bit cheaper and more affordable than the more famous brands."
    ),
    brandCreate(
      "PNY", 
      "PNY is an American company that makes graphics cards, flash memory cards, flash drives, chargers, adapters, and other accessories. PNY makes both gaming and workstation graphics cards for Nvidia."
    ),
    brandCreate(
      "Palit", 
      "Palit is a graphics card manufacturer that mainly makes Nvidia Graphics Cards. It is a fairly popular brand and offers some cheap graphics cards."
    ),
    brandCreate(
      "PowerColor", 
      "PowerColor is an AMD Radeon Graphics Cards manufacturer from Taiwan. It is a good brand and if you are looking for an AMD Graphics Card then PowerColor is one of the best."
    ),
    brandCreate(
      "Sapphire", 
      "Sapphire also makes AMD Graphics Cards. It offers AMD Radeon graphics cards from all ranges including budget, mid-range, and high-end graphics cards. Sapphire is one of the most popular brands for AMD Radeon graphics cards."
    ),
    brandCreate(
      "Inno3D", 
      "Inno3D is a Chinese manufacturer of Nvidia Graphics Cards. Their graphics cards offer good performance but they are a bit hard to find because of availability issues."
    ),
    brandCreate(
      "XFX", 
      "XFX used to make Nvidia graphics cards previously but it is no longer an official Nvidia Partner and now it only makes AMD Graphics Cards. XFX Graphics Cards are pretty good and offer great performance and features."
    ),
    brandCreate(
      "HIS", 
      "HIS is a graphics card manufacturer that makes AMD Radeon Graphics Cards."
    ),
    brandCreate(
      "VisionTek", 
      "VisionTek is a manufacturer of AMD Radeon Graphics Cards. Their graphics cards are not very popular among gamers and also they are not readily available."
    ),
    brandCreate(
      "ASRock", 
      "ASRock, which is known for its motherboards manufactures AMD Radeon Gaming Graphics Cards. Their graphics card series or range is known as Phantom Gaming."
    ),
    brandCreate(
      "AFOX", 
      "AFOX is a Hong Kong-based company that manufactures both Nvidia and AMD graphics cards. It also manufactures Motherboards, Memory, SSD, CPU cooler, Power Supply, Mini-PC, Tablet PC, and Laptops."
    ),
    brandCreate(
      "Manli", 
      "Manli Technology Group Ltd. is one of the major manufacturers and suppliers of Computer Graphics Cards, MiniPCs, 3D Printers, and other peripherals/components. It is a Hong Kong-based company and makes only Nvidia graphics cards."
    ),
    brandCreate(
      "AMD", 
      "Advanced Micro Devices, Inc., commonly abbreviated as AMD, is an American multinational semiconductor company based in Santa Clara, California, that develops computer processors and related technologies for business and consumer markets."
    ),
    brandCreate(
      "Intel", 
      "Intel Corporation (commonly known as Intel) is an American multinational corporation and technology company headquartered in Santa Clara, California. It is one of the world's largest semiconductor chip manufacturer by revenue, and is one of the developers of the x86 series of instruction sets found in most personal computers (PCs)."
    ),
    brandCreate(
      "Nvidia", 
      "Nvidia Corporation is an American multinational technology company incorporated in Delaware and based in Santa Clara, California. It is a software and fabless company which designs graphics processing units (GPUs), application programming interface (APIs) as well as system on a chip units (SoCs)."
    ),
    brandCreate(
      "Be Quiet!", 
      "Be Quiet! is a computer hardware brand owned by the German company Listan GmbH, which manufactures power supply units, CPU coolers, computer cases and case fans. The main target groups for products in the be quiet! range are PC enthusiasts and gamers as well as smaller and larger PC integrators."
    ),    
    brandCreate(
      "Thermaltake", 
      "Thermaltake Technology Co. Ltd is a Taiwanese manufacturer of PC case designs, power supplies, cooling devices and peripherals. Its main headquarters are located in Taipei, Taiwan. It has multiple manufacturing facilities in mainland China, including a major plant at Dongguan."
    ),    
    brandCreate(
      "Thermalright", 
      "Thermalright Inc. is a Taiwan-based company headquartered in Taipei, and established in 2001. The company produces aftermarket heat sinks and other components for cooling desktop computers."
    ),    
    brandCreate(
      "Deepcool", 
      "DeepCool is a computer hardware manufacturer headquartered in Beijing, China. Founded in 1996, the company produces a range of products including air and water CPU coolers, computer cases, power supplies, computer peripherals, and accessories."
    ),    
    brandCreate(
      "Noctua", 
      "Noctua is an Austrian computer hardware manufacturer of CPU-coolers and computer fans which is primarily aimed at the enthusiast market. "
    ),    
    brandCreate(
      "Zalman", 
      "Zalman Tech Co. (usually simplified as ZALMAN) is a South Korean company that develops and provides aftermarket desktop computer products with primary focus on cooling enhancement."
    ),    
    brandCreate(
      "Cooler Master", 
      "Cooler Master Technology Inc. is a computer hardware manufacturer based in Taiwan. Founded in 1992, the company produces computer cases, power supplies, air and liquid CPU coolers, laptop cooling pads, and computer peripherals."
    ),
    brandCreate(
      "Corsair", 
      "Corsair Gaming, Inc. is an American computer peripherals and hardware company based in Milpitas, California. It designs and sells high-speed DRAM modules, ATX power supplies (PSUs), USB flash drives (UFDs), CPU/GPU and case cooling and gaming peripherals."
    ),
    brandCreate(
      "NZXT", 
      "NZXT is an American computer hardware manufacturer based in Los Angeles, California. The company manufactures computer cases, components, and accessories for the PC gaming market."
    ),
    brandCreate(
      "Kingston", 
      "Kingston Technology Corporation is an American multinational computer technology corporation that develops, manufactures, sells and supports flash memory products, other computer-related memory products, as well as the HyperX gaming division (now owned by HP)."
    ),
    brandCreate(
      "GSkill", 
      "G.SKILL International Enterprise is a Taiwanese computer hardware manufacturing company.[1] The company's target customers are overclocking computer users. It produces a variety of high-end PC products and is best known for its DRAM products."
    ),
    brandCreate(
      "Adata", 
      "ADATA Technology Co. Ltd. is a Taiwanese fabless memory, storage and computer case manufacturer, founded in May 2001 by Simon Chen. Its main product line consists of DRAM modules, USB Flash drives, hard disk drives, solid state drives, memory cards and mobile accessories."
    ),    
    brandCreate(
      "Silicon Power", 
      "Silicon Power Computer & Communications Incorporated, is an international brand and a Taiwan-based manufacturer of flash memory products, including flash memory cards, USB flash drives, portable hard drives, DRAM modules, card readers, solid state drives, USB adapters, and other industrial grade computer products."
    ),
    brandCreate(
      "Seagate", 
      "Seagate Technology Holdings plc is an American data storage company. It was incorporated in 1978 as Shugart Technology and commenced business in 1979. Seagate developed the first 5.25-inch hard disk drive (HDD), the 5-megabyte ST-506, in 1980."
    ),
    brandCreate(
      "Western Digital", 
      "Western Digital Corporation is an American computer drive manufacturer and data storage company, headquartered in San Jose, California. It designs, manufactures and sells data technology products, including data storage devices, data center systems and cloud storage services."
    ),    
    brandCreate(
      "Lian Li", 
      "Lian Li Industrial Co., Ltd. is a Taiwanese computer case and accessories manufacturer. It is one of the largest manufacturers of aluminium computer cases in Taiwan and is also a major world competitor in the premium aftermarket computer case industry."
    ),
    brandCreate(
      "Fractal Design", 
      "Fractal Design is a computer hardware manufacturer from Sweden. Founded in 2007, the company manufactures computer cases, water coolers, case fans, and power supplies. All products are designed and engineered in Sweden."
    ),    
    brandCreate(
      "Phanteks", 
      "Phanteks is a Dutch company which mainly produces PC cases, fans and other case accessories. The company has a base in the United States."
    ),    
  ]);
}

async function createComponents() {
  console.log("Adding Components");
  await Promise.all([
    componentCreate(
      "GIGABYTE B650 AORUS Elite AX",
      categories["Motherboard"],
      brands["Gigabyte"],
      "GIGABYTE B650 AORUS Elite AX (AM5/ LGA 1718/ AMD B650/ ATX/ 5-Year Warranty/ DDR5/ M.2/ PCIe 5.0/ USB 3.2 Gen2X2 Type-C/WiFi 6E/ 2.5GbE LAN/Q-Flash Plus/EZ-Latch/Gaming Motherboard)",
      214.99,
      ""
    ),
    componentCreate(
      "GIGABYTE Z790 AORUS Master",
      categories["Motherboard"],
      brands["Gigabyte"],
      "GIGABYTE Z790 AORUS Master (LGA 1700/ Intel Z790/ EATX/ DDR5/ 5* M.2/ PCIe 5.0/ USB 3.2 Gen2X2 Type-C/Intel WiFi 6E/ Marvell AQtion 10GbE LAN/Q-Flash Plus/EZ-Latch Plus/Gaming Motherboard)",
      466.03,
      ""
    ),
    componentCreate(
      "GIGABYTE GeForce RTX™ 2070 GAMING WINDFORCE 3X",
      categories["Video Card"],
      brands["Gigabyte"],
      "Powered by GeForce RTX™ 2070, Integrated with 8GB GDDR6 256-bit memory interface WINDFORCE 3X Cooling System with alternate spinning fans RGB Fusion 2.0 Metal Back Plate",
      319.99,
      ""
    ),
    componentCreate(
      "GIGABYTE GeForce RTX 4070 AERO OC 12G",
      categories["Video Card"],
      brands["Gigabyte"],
      "Gigabyte GeForce RTX 4070 AERO OC 12G Graphics Card, 3X WINDFORCE Fans, 12GB 192-bit GDDR6X, GV-N4070AERO OC-12GD Video Card",
      659.99,
      ""
    ),
    componentCreate(
      "GIGABYTE GeForce RTX 3060 Gaming OC 12G",
      categories["Video Card"],
      brands["Gigabyte"],
      "GIGABYTE GeForce RTX 3060 Gaming OC 12G (REV2.0) Graphics Card, 3X WINDFORCE Fans, 12GB 192-bit GDDR6, GV-N3060GAMING OC-12GD Video Card",
      319.99,
      ""
    ),
    componentCreate(
      "GIGABYTE GeForce RTX 3070 Gaming OC 8G",
      categories["Video Card"],
      brands["Gigabyte"],
      "GIGABYTE GeForce RTX 3070 Gaming OC 8G (REV2.0) Graphics Card, 3X WINDFORCE Fans, LHR, 8GB 256-bit GDDR6, GV-N3070GAMING OC-8GD Video Card",
      499.99,
      ""
    ),
    componentCreate(
      "AMD Ryzen 9 5900X",
      categories["CPU"],
      brands["AMD"],
      "AMD Ryzen 9 5900X 12-core, 24-Thread Unlocked Desktop Processor",
      297.00,
      ""
    ),
    componentCreate(
      "AMD Ryzen 5 5600X",
      categories["CPU"],
      brands["AMD"],
      "AMD Ryzen 5 5600X 6-core, 12-Thread Unlocked Desktop Processor with Wraith Stealth Cooler",
      297.00,
      ""
    ),
    componentCreate(
      "AMD Ryzen 7 5800X",
      categories["CPU"],
      brands["AMD"],
      "AMD Ryzen 7 5800X 8-core, 16-Thread Unlocked Desktop Processor",
      229.00,
      ""
    ),
    componentCreate(
      "AMD Ryzen 7 5700G",
      categories["CPU"],
      brands["AMD"],
      "AMD Ryzen 7 5700G 8-Core, 16-Thread Unlocked Desktop Processor with Radeon Graphics",
      177.10,
      ""
    ),
    componentCreate(
      "AMD Ryzen 9 7900X",
      categories["CPU"],
      brands["AMD"],
      "AMD Ryzen™ 9 7900X 12-Core, 24-Thread Unlocked Desktop Processor",
      425.00,
      ""
    ),
    componentCreate(
      "Intel Core i5-12600K",
      categories["CPU"],
      brands["Intel"],
      "Intel Core i5-12600K Desktop Processor with Integrated Graphics and 10 (6P+4E) Cores up to 4.9 GHz Unlocked LGA1700 600 Series Chipset 125W",
      196.99,
      ""
    ),
    componentCreate(
      "Intel Core i7-12700K",
      categories["CPU"],
      brands["Intel"],
      "Intel Core i7-12700K Gaming Desktop Processor with Integrated Graphics and 12 (8P+4E) Cores up to 5.0 GHz Unlocked  LGA1700 600 Series Chipset 125W",
      252.73,
      ""
    ),
    componentCreate(
      "Intel Core i9-13900K",
      categories["CPU"],
      brands["Intel"],
      "Intel Core i9-13900K (Latest Gen) Gaming Desktop Processor 24 cores (8 P-cores + 16 E-cores) with Integrated Graphics - Unlocked",
      425.00,
      ""
    ),
    componentCreate(
      "Intel Core i7-12700K",
      categories["CPU"],
      brands["Intel"],
      "Intel Core i7-12700K Gaming Desktop Processor with Integrated Graphics and 12 (8P+4E) Cores up to 5.0 GHz Unlocked  LGA1700 600 Series Chipset 125W",
      252.73,
      ""
    ),
    componentCreate(
      "MSI Gaming Radeon RX 6750 XT",
      categories["Video Card"],
      brands["MSI"],
      "MSI Gaming Radeon RX 6750 XT 192-bit 12GB GDDR6 Boost Clock 2600MHz Dual Torx 3.0 Fans DP/HDMI FreeSync DirectX 12 VR",
      379.99,
      ""
    ),
    componentCreate(
      "MSI Gaming GeForce RTX 3060 Ti",
      categories["Video Card"],
      brands["MSI"],
      "MSI Gaming GeForce RTX 3060 Ti LHR 8GB GDRR6X, 256-Bit, HDMI/DP, Nvlink, Torx Fan 3, Ampere Architecture OC Graphics Card (RTX)",
      339.99,
      ""
    ),
    componentCreate(
      "MSI Gaming GeForce RTX 4070 Ti",
      categories["Video Card"],
      brands["MSI"],
      "MSI Gaming GeForce RTX 4070 Ti 12GB GDRR6X 192-Bit HDMI/DP Nvlink Tri-Frozr 3 Ada Lovelace Architecture Graphics Card (RTX 4070)",
      479.99,
      ""
    ),
    componentCreate(
      "MSI Gaming GeForce RTX 4090",
      categories["Video Card"],
      brands["MSI"],
      "MSI Gaming GeForce RTX 4090 24GB GDRR6X 384-Bit HDMI/DP Nvlink Tri-Frozr 3 Ada Lovelace Architecture OC Graphics Card (RTX 4090 SUPRIM X)",
      1749.99,
      ""
    ),
    componentCreate(
      "MSI Gaming GeForce RTX 3060",
      categories["Video Card"],
      brands["MSI"],
      "MSI Gaming GeForce RTX 3060 12GB 15 Gbps GDRR6 192-Bit HDMI/DP PCIe 4 Torx Triple Fan Ampere OC Graphics Card (RTX 3060 Ventus 3X)",
      279.99,
      ""
    ),
    componentCreate(
      "MSI MAG B660M Mortar",
      categories["Motherboard"],
      brands["MSI"],
      "MSI MAG B660M Mortar WiFi DDR4 Gaming Motherboard (mATX, 12th Gen Intel Core, LGA 1700 Socket, DDR4, PCIe 4, 2.5G LAN, M.2 Slots, Wi-Fi 6)",
      179.99,
      ""
    ),
    componentCreate(
      "MSI PRO B760M-P DDR4",
      categories["Motherboard"],
      brands["MSI"],
      "MSI PRO B760M-P DDR4 ProSeries Motherboard (Supports 12th/13th Gen Intel Processors, LGA 1700, DDR4, PCIe 4.0, M.2, Gbps LAN, USB",
      107.74,
      ""
    ),
    componentCreate(
      "MSI MPG X570S Carbon",
      categories["Motherboard"],
      brands["MSI"],
      "MSI MPG X570S Carbon EK X Gaming Motherboard (ATX, AMD, Socket AM4. DDR4, PCIe 4, CFX, M.2 Slots, Wi-Fi 6E)",
      389.99,
      ""
    ),
    componentCreate(
      "EVGA CLC 360mm All-in-One LCD CPU Liquid Cooler",
      categories["CPU Cooler"],
      brands["EVGA"],
      "EVGA CLC 360mm All-in-One LCD CPU Liquid Cooler, 3X 120mm PWM ARGB Fans, Intel, AMD, 5 YR Warranty, 400-HY-CX36-V1",
      65.00,
      ""
    ),
    componentCreate(
      "EVGA SuperNOVA 1000 GT, 80 Plus Gold 1000W",
      categories["Power Supply"],
      brands["EVGA"],
      "EVGA SuperNOVA 1000 GT, 80 Plus Gold 1000W, Fully Modular, Eco Mode with FDB Fan, 10 Year Warranty, Includes Power ON Self Tester, Compact 150mm Size, Power Supply 220-GT-1000-X1",
      389.99,
      ""
    ),
    componentCreate(
      "EVGA Supernova 1600 G+, 80+ Gold 1600W",
      categories["Power Supply"],
      brands["EVGA"],
      "EVGA Supernova 1600 G+, 80+ Gold 1600W, Fully Modular, 10 Year Warranty, Includes Free Power On Self Tester, Power Supply 220-GP-1600-X1",
      249.00,
      ""
    ),
    componentCreate(
      "EVGA Geforce RTX 3060 Xc Gaming",
      categories["Video Card"],
      brands["EVGA"],
      "EVGA Geforce RTX 3060 Xc Gaming (12Gb Gddr6/Pci Express 4.0/1882Mhz/15000Mhz), 12G-P5-3657-KR",
      476.09,
      ""
    ),
    componentCreate(
      "EVGA GeForce RTX 3090 Ti",
      categories["Video Card"],
      brands["EVGA"],
      "EVGA GeForce RTX 3090 Ti FTW3 Ultra Gaming, 24G-P5-4985-KR, 24GB GDDR6X, iCX3, ARGB LED, Backplate, Free eLeash",
      1949.00,
      ""
    ),
    componentCreate(
      "ZOTAC Gaming GeForce RTX 3060",
      categories["Video Card"],
      brands["Zotac"],
      "ZOTAC Gaming GeForce RTX 3060 Twin Edge OC 12GB GDDR6 192-bit 15 Gbps PCIE 4.0 Graphics Card, IceStorm 2.0 Cooling, Active Fan Control, Freeze Fan Stop ZT-A30600H-10M",
      322.07,
      ""
    ),
    componentCreate(
      "ZOTAC GeForce GTX 1660 Super",
      categories["Video Card"],
      brands["Zotac"],
      "ZOTAC GeForce GTX 1660 Super 6GB GDDR6 192-bit Gaming Graphics Card, Super Compact, ZT-T16620F-10L",
      259.45,
      ""
    ),
    componentCreate(
      "ZOTAC Gaming GeForce RTX 4080",
      categories["Video Card"],
      brands["Zotac"],
      "ZOTAC Gaming GeForce RTX 4080 16GB AMP Extreme AIRO GDDR6X 256-bit 22.4 Gbps PCIE 4.0 Graphics Card, IceStorm 2.0 Advanced Cooling, Spectra 2.0 RGB Lighting, ZT-D40810B-10P",
      1333.64,
      ""
    ),
    componentCreate(
      "PNY XLR8 Gaming 16GB (2x8GB) DDR4 DRAM 3200MHz",
      categories["Memory"],
      brands["PNY"],
      "PNY XLR8 Gaming 16GB (2x8GB) DDR4 DRAM 3200MHz (PC4-25600) CL16 1.35V Dual Channel Desktop (DIMM) Memory Kit - MD16GK2D4320016AXR",
      45.32,
      ""
    ),
    componentCreate(
      "PNY EliteX-PRO 2TB USB 3.2 Gen 2x2 Type-C Portable Solid State Drive (SSD)",
      categories["Storage"],
      brands["PNY"],
      "PNY EliteX-PRO 2TB USB 3.2 Gen 2x2 Type-C Portable Solid State Drive (SSD) - (PSD0CS2260-2TB-RB)",
      133.64,
      ""
    ),
    componentCreate(
      "PNY XLR8 CS3140 1TB M.2 NVMe",
      categories["Storage"],
      brands["PNY"],
      "PNY XLR8 CS3140 1TB M.2 NVMe Gen4 x4 Internal Solid State Drive (SSD) - M280CS3140-1TB-RB",
      153.64,
      ""
    ),
    componentCreate(
      "PNY Performance 8GB DDR4 DRAM 3200MHz",
      categories["Memory"],
      brands["PNY"],
      "PNY Performance 8GB DDR4 DRAM 3200MHz (PC4-25600) CL22 (Compatible with 2933MHz, 2666MHz, 2400MHz or 2133MHz) 1.2V Notebook/Laptop (SODIMM) Computer Memory Kit - MN8GSD43200-TB",
      16.99,
      ""
    ),
    componentCreate(
      "PowerColor Fighter AMD Radeon RX 6700 XT",
      categories["Video Card"],
      brands["PowerColor"],
      "PowerColor Fighter AMD Radeon RX 6700 XT Gaming Graphics Card with 12GB GDDR6 Memory, Powered by AMD RDNA 2, Raytracing, PCI Express 4.0, HDMI 2.1, AMD Infinity Cache",
      349.99,
      ""
    ),
    componentCreate(
      "PowerColor AMD Radeon RX 6500 XT",
      categories["Video Card"],
      brands["PowerColor"],
      "PowerColor AMD Radeon RX 6500 XT ITX Gaming Graphics Card with 4GB GDDR6 Memory",
      156.99,
      ""
    ),
    componentCreate(
      "PowerColor AMD Radeon RX 7900 XT Graphics Card",
      categories["Video Card"],
      brands["PowerColor"],
      "PowerColor AMD Radeon RX 7900 XT Graphics Card",
      216.99,
      ""
    ),
    componentCreate(
      "Sapphire 11322-01-40G Nitro+ AMD Radeon RX 7900 XTX",
      categories["Video Card"],
      brands["Sapphire"],
      "Sapphire 11322-01-40G Nitro+ AMD Radeon RX 7900 XTX Vapor-X Gaming Graphics Card with 24GB GDDR6, AMD RDNA 3",
      1049.99,
      ""
    ),
    componentCreate(
      "Sapphire 11308-03-20G Nitro+ AMD Radeon RX 6900 XT",
      categories["Video Card"],
      brands["Sapphire"],
      "Sapphire 11308-03-20G Nitro+ AMD Radeon RX 6900 XT Special Edition PCIe 4.0 Gaming Graphics Card with 16GB GDDR6",
      1499.00,
      ""
    ),
    componentCreate(
      "Sapphire 11310-04-20G Pulse AMD Radeon RX 6600",
      categories["Video Card"],
      brands["Sapphire"],
      "Sapphire 11310-04-20G Pulse AMD Radeon RX 6600 LITE Edition HDMI DP Gaming Graphics Card with 8GB GDDR6, AMD RDNA 2",
      280.99,
      ""
    ),
    componentCreate(
      "ASRock X670E Taichi Carrara",
      categories["Motherboard"],
      brands["ASRock"],
      "ASRock X670E Taichi Carrara Support AMD AM5 RYZEN 7000 Series Processors Motherboard",
      573.03,
      ""
    ),
    componentCreate(
      "srock Z490 Phantom Gaming ITX/TB3",
      categories["Motherboard"],
      brands["ASRock"],
      "Asrock Z490 Phantom Gaming ITX/TB3 Supports 10 th Gen and Future Generation Intel Core Motherboard Processors (Socket 1200), Model Number: Z490 Phantom Gaming-ITX/TB3",
      159.99,
      ""
    ),
    componentCreate(
      "ASRock A520M-ITX/AC",
      categories["Motherboard"],
      brands["ASRock"],
      "ASRock A520M-ITX/AC Supports 3rd Gen AMD AM4 Ryzen™ / Future AMD Ryzen™ Processors (3000 and 4000 Series Processors) Motherboard",
      107.73,
      ""
    ),
    componentCreate(
      "Nvidia GeForce GTX 1070",
      categories["Video Card"],
      brands["Nvidia"],
      "Nvidia GeForce GTX 1070 Founders Edition - 900-1G411-2520-001",
      269.99,
      ""
    ),
    componentCreate(
      "Nvidia GeForce GTX 1080",
      categories["Video Card"],
      brands["Nvidia"],
      "Nvidia GeForce GTX 1080 8GB FE Founders Edition GDDR5X Video Graphics Card",
      319.99,
      ""
    ),
    componentCreate(
      "NVIDIA GeForce RTX 4070",
      categories["Video Card"],
      brands["Nvidia"],
      "NVIDIA GeForce RTX 4070 Founder's Edition (FE) Graphics Card - Titanium and Black",
      269.99,
      ""
    ),
    
  ]);
}
